# copied from
# https://github.com/ledgetech/lua-resty-http/blob/master/.github/workflows/test.yml

name: Test

on:
  push:
    paths-ignore: # Skip if only docs are updated
        - '*.md'

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "luajit-openresty"
    - uses: leafo/gh-actions-luarocks@v4
    - run: luarocks install luacheck
    - run: luacheck lib --no-unused

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install OpenResty
      # trying to get the openresty and redis containers to talk to each other was a nightmare
      run: |
        # install OpenResty
        sudo apt-get -y install --no-install-recommends wget gnupg ca-certificates
        wget -O - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
        echo "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/openresty.list
        sudo apt-get update
        sudo apt-get -y install openresty
        sudo systemctl stop openresty
        # remove nginx
        sudo apt-get remove nginx
        which openresty
        which nginx

    - name: Install Redis
      # several tests require Redis
      # note: if tests hang, it could be because the Redis version has changed
      run: |
        sudo apt-get install redis luarocks

    - name: Install Deps
      run: |
        sudo apt-get install perl libperl-dev cpanminus
        # our openesty depenedencies
        sudo opm get ledgetech/lua-resty-http

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cpan
          ~/.cache
        key: ${{ runner.os }}-${{ matrix.openresty_version }}-cache

    - name: Install Test::Nginx
      run: sudo cpanm -q -n Test::Nginx

    - name: Install Luacov
      run: sudo luarocks install luacov

    - name: Run tests
      env:
        TEST_COVERAGE: '1'
        # use redis for the host here because we have specified a container for the job.
        # If we were running the job on the VM this would be localhost
      run: |
         /usr/bin/prove -I../test-nginx/lib -r t/
      continue-on-error: true

    - name: Run tests A again for cat
      env:
        TEST_COVERAGE: '1'
      run: |
         /usr/bin/prove -I../test-nginx/lib -r t/certificate_serving/03_redis_cache_prime_1.t
      continue-on-error: true

    - name: SHOW ME THE ERROR
      run: |
         cat t/servroot/logs/error.log


    - name: Coverage
      run: |
        luacov
        tail -n 8 luacov.report.out
